#!/bin/bash

#######################################################################
git-quote - adds quotations after commit message and calls commit
#######################################################################
    Copyright (C) {2012}  {Tomasz Borek}

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#######################################################################

TMP=youSeeWhatsAlreadyGone
DEBUG=0

function debugAndExit() {
	if [ $DEBUG -eq 1 ]
	  then
	    echo "$1"
	    echo "Commit message was: "
	    cat $TMP
	    rm $TMP
	    exit
	fi
}

if [ $# -eq 0 ]
then
  echo "Składnia: `basename $0` [-d] opis_zmiany [plik1] [plik2] ... [plikN]. Bez plików oznacza git commit -a."
  echo "          -d -> debug, wypisuje na ekran, nie wykonuje zmian."
  exit
fi

if [ "$1" == "-d" ]
then
  DEBUG=1
  shift
fi

echo "$1 " > $TMP
echo >> $TMP
echo >> $TMP
echo "$(fortune prQ)" >> $TMP

if [ $# -eq 1 ]
then
  debugAndExit "1: -a"
  git commit -aF $TMP
else
  debugAndExit "Params (beside -d):
    total: $#
    given: $*"
  git commit -F $TMP $*
fi
echo "Zmieniono indeks. $*"
rm $TMP
