#!/bin/sh
#Generated with love at wt. kwi 21 08:24:49 2020 by JetBrains Toolbox 1.8.3678 (Mar 15 2018)

"/home/tammo/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/192.6817.19/bin/pycharm.sh" "$@"

