#!/bin/bash

#######################################################################
# git-quote - adds quotations after commit message and calls commit
#######################################################################
#  Copyright (C) {2012-2021}  {Tomasz Borek}
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#######################################################################

TMP=youSeeWhatsAlreadyGone
DEBUG=0

function debugAndExit() {
	if [ $DEBUG -eq 1 ]
	  then
	    echo "$1"
        echo "Commit message was: $(< $TMP)"
	    rm $TMP
	    exit 0
	fi
}

if [ $# -eq 0 ]
then
  echo "Usage: `basename $0` [-d] commit_message [file1] [file2] ... [fileN]. No files => git commit -aevF."
  echo "          -d -> debug, writes to console only, no changes."
  exit
fi

if [ "$1" == "-d" ]
then
  DEBUG=1
  set -v
  shift
fi

echo "$1 " > $TMP
echo >> $TMP
echo >> $TMP
echo "$(fortune prQ)" >> $TMP

if [ $# -eq 1 ]
then
  debugAndExit "Only description given: commit -aevF"
  git commit -aevF $TMP
else
  shift # skipping commit msg
  debugAndExit "Files given => commit -evF. Params (beside -d and commit message):
    total: $#
    given: $*"
  git commit -evF $TMP $*
fi
echo "Exit status is $? Parameters passed were $* . Removing temporary file $TMP"
rm $TMP
