Git-quote
---------

A fun side-project, when I was learning Git. Uses `fortune` and `git` to append a random quote to git log message. If git-quote is on your PATH, then it effectively extends Git with new subcommand, quote.

=== Howto

* clone the repository
* `sudo apt-get install fortune` if you don't have it already
* put prQ file where fortune was installed (`/usr/share/games/fortune` ?)

==== If you want your own fortune file

http://ubuntuforums.org/showthread.php?t=1343692[Ubuntu Forum] (specifically **Qrwe**) provides. In case the link doesn't work:

. create a text file with `%` as separator lines between fortunes
.. separator lines means just one `%` occupies one whole line between entries
. move the file to fortune directory
. `strfile -c % yourFortuneFile yourFortuneFile.dat`

Remarks:

. fortune operates on `dat` file, not on text file. You edit a text and `strfile` it again if you want your change to be seen while using fortune
. `strfile` converts text into structural file, with header and offsets - allows randomization of quotes
. moving to fortune dir allows fortune to use it simply, with no path to fortune file given, just `fortune yourFortuneFile`, no `fortune your/path/to/yourFortuneFile`

Again - credits for this README section go to **Qrwe** from Ubuntu Forums.

=== Adding your own quotes

Is quite simple, there's script for that. Just run it and it will ask you for quote text and it's author, append them to `prQ` file in proper format and later convert the file into `DAT` format and put it where `fortune` is usually installed.

For different place, modify `$FORTUNE_PATH` in the script.
For now bulk addition is not supported as I never needed it.
